cse-valid-runner:
  eic-codes:
    austria: 10YAT-APG------L
    france: 10YFR-RTE------C
    italy: 10YIT-GRTN-----B
    slovenia: 10YSI-ELES-----O
    switzerland: 10YCH-SWISSGRIDZ

retry:
  backoff:
    delay: 3000 # 3s delay before first retry
    multiplier: 2
  max-attempts: 5 # the first attempt + 4 potential retry