logback:
  amqp:
    exchange: cse-valid-idcc-task-manager-logs-exchange
    routing-key: "#"
spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:gridcapa}
    password: ${RABBITMQ_PASSWORD:gridcapa}
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      bindings:
        task-status-update:
          destination: cse-valid-idcc-task-status-updated

rao-runner-server:
  amqp:
    client-app-id: cse-valid-idcc-runner
    queue-name: rao-request-queue

cse-valid-runner:
  async-time-out: 600000
  bindings:
    request:
      destination: cse-valid-idcc-requests
      routing-key: "#"
    response:
      destination: cse-valid-idcc-response
      expiration: 600000
  whitelist:
    - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
    - http://minio:9000

minio-adapter:
  bucket: gridcapa
  base-path: CSE/VALID
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000/